// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneroMarketCap.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneroMarketCap.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414193855_AddCoinPriceHistory")]
    partial class AddCoinPriceHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneroMarketCap.Data.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ath")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AthChangePercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("AthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Atl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AtlChangePercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("AtlDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CirculatingSupply")
                        .HasColumnType("numeric");

                    b.Property<string>("CoinGeckoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FullyDilutedValuation")
                        .HasColumnType("numeric");

                    b.Property<decimal>("High24h")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Low24h")
                        .HasColumnType("numeric");

                    b.Property<int>("MarketCapRank")
                        .HasColumnType("integer");

                    b.Property<decimal>("MarketCapUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxSupply")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceChangePercent1h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChangePercent24h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChangePercent30d")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChangePercent7d")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalSupply")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.CoinPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CirculatingSupply")
                        .HasColumnType("numeric");

                    b.Property<int>("CoinId")
                        .HasColumnType("integer");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MarketCapUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.ToTable("CoinPriceHistory");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.CoinTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PortfolioCoinId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceUsdAtTime")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TransactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioCoinId");

                    b.ToTable("CoinTransactions");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.PortfolioCoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCostBasis")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.HasIndex("PortfolioId", "CoinId")
                        .IsUnique();

                    b.ToTable("PortfolioCoins");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.CoinPriceHistory", b =>
                {
                    b.HasOne("MoneroMarketCap.Data.Models.Coin", "Coin")
                        .WithMany("PriceHistory")
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.CoinTransaction", b =>
                {
                    b.HasOne("MoneroMarketCap.Data.Models.PortfolioCoin", "PortfolioCoin")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioCoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioCoin");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.Portfolio", b =>
                {
                    b.HasOne("MoneroMarketCap.Data.Models.AppUser", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.PortfolioCoin", b =>
                {
                    b.HasOne("MoneroMarketCap.Data.Models.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneroMarketCap.Data.Models.Portfolio", "Portfolio")
                        .WithMany("PortfolioCoins")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.UserRole", b =>
                {
                    b.HasOne("MoneroMarketCap.Data.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneroMarketCap.Data.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.AppUser", b =>
                {
                    b.Navigation("Portfolios");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.Coin", b =>
                {
                    b.Navigation("PriceHistory");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.Portfolio", b =>
                {
                    b.Navigation("PortfolioCoins");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.PortfolioCoin", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneroMarketCap.Data.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
